"""Keep ``dagster.yaml`` topology and the Komodo Resource Sync TOML in lockstep.

The set of Docker hosts and which code locations run on each is declared in
``dagster.yaml`` ``docker_hosts`` *and* (under GitOps) in Komodo's Resource Sync
TOML as ``[[server]]`` / ``[[stack]]`` entries. If the two drift, runs can fail
silently — most insidiously, a code location that Komodo deploys but that is
missing from ``docker_hosts`` falls through to the ``DefaultRunLauncher`` instead
of running as a remote container.

This module provides the pure pieces behind ``komodo-export`` (generate the TOML
skeleton from ``dagster.yaml``) and ``komodo-verify`` (diff ``dagster.yaml``
against a Komodo Resource Sync TOML file).

Convention used for the mapping:

* each ``docker_hosts[].host_name`` ↔ a ``[[server]]`` whose ``name`` matches it
* each code location ↔ a ``[[stack]]`` whose ``name`` is the location name and
  whose ``server`` (top-level or under ``config``) is the location's host
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List
from urllib.parse import urlparse

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover - exercised on <3.11
    import tomli as tomllib

from dagster_multihost_launcher.cli.config import DeployConfig

# -- export ------------------------------------------------------------------


def _periphery_host_hint(docker_url: str) -> str:
    """Best-effort host extracted from a Docker URL, for a TODO comment."""
    if not docker_url:
        return "localhost"
    parsed = urlparse(docker_url)
    return parsed.hostname or docker_url


def generate_resource_sync_toml(config: DeployConfig) -> str:
    """Generate a Komodo Resource Sync TOML skeleton from a DeployConfig.

    Emits one ``[[server]]`` per Docker host and one ``[[stack]]`` per code
    location. Connection-specific fields (the Periphery address, image, etc.)
    are left as TODO comments to fill in — this is a starting point, not a
    drop-in file.
    """
    lines: List[str] = [
        "# Generated by `dagster-multihost komodo-export`.",
        "# A starting skeleton — fill in the TODOs (Periphery address, compose,",
        "# images) and commit to your Komodo Resource Sync repo.",
        "",
    ]

    for host in config.docker_hosts.values():
        hint = _periphery_host_hint(host.docker_url or "")
        lines.append("[[server]]")
        lines.append(f'name = "{host.host_name}"')
        lines.append("[server.config]")
        lines.append(f'address = "https://{hint}:8120"  # TODO: Periphery address')
        lines.append("enabled = true")
        lines.append("")

    for host in config.docker_hosts.values():
        for location in host.location_names:
            lines.append("[[stack]]")
            lines.append(f'name = "{location}"')
            lines.append("[stack.config]")
            lines.append(f'server = "{host.host_name}"')
            lines.append("# TODO: file_contents / repo + run_directory for compose")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# -- verify ------------------------------------------------------------------


@dataclass
class TopologyDiff:
    """Result of diffing dagster.yaml docker_hosts vs a Komodo TOML."""

    # Errors (would break run routing):
    missing_servers: List[str] = field(default_factory=list)
    missing_stacks: List[str] = field(default_factory=list)
    misplaced_stacks: List[str] = field(default_factory=list)
    # Informational:
    extra_servers: List[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not (
            self.missing_servers or self.missing_stacks or self.misplaced_stacks
        )


def _stack_server(stack: Dict[str, Any]) -> Any:
    """Pull a stack's target server, whether at top level or under ``config``."""
    if "server" in stack:
        return stack["server"]
    return (stack.get("config") or {}).get("server")


def load_komodo_toml(path: str) -> Dict[str, Any]:
    """Read a Komodo Resource Sync TOML file into a dict."""
    with open(path, "rb") as f:
        return tomllib.load(f)


def diff_topology(config: DeployConfig, komodo: Dict[str, Any]) -> TopologyDiff:
    """Diff dagster.yaml docker_hosts against a parsed Komodo Resource Sync doc.

    ``komodo`` is the dict from :func:`load_komodo_toml` (``[[server]]`` /
    ``[[stack]]`` become lists under the ``server`` / ``stack`` keys).
    """
    diff = TopologyDiff()

    komodo_servers = {s.get("name") for s in komodo.get("server", []) if s.get("name")}
    komodo_stacks = {
        s.get("name"): _stack_server(s)
        for s in komodo.get("stack", [])
        if s.get("name")
    }

    dagster_hosts = set(config.docker_hosts.keys())

    # Servers declared in dagster.yaml but absent from Komodo
    for host in sorted(dagster_hosts):
        if host not in komodo_servers:
            diff.missing_servers.append(host)

    # Komodo servers not referenced by dagster.yaml (informational)
    for server in sorted(komodo_servers - dagster_hosts):
        diff.extra_servers.append(server)

    # Each code location should have a stack on its expected host
    for location, host in sorted(config.location_to_host.items()):
        if location not in komodo_stacks:
            diff.missing_stacks.append(location)
        elif komodo_stacks[location] != host:
            diff.misplaced_stacks.append(
                f"{location}: dagster.yaml=>{host}, komodo=>"
                f"{komodo_stacks[location]}"
            )

    return diff
